import discord
from discord.ext import commands
import pandas as pd

import csv
import numpy as np

prompts = (
    "What is the **TITLE** of the **HOST** message?",
    "What is the **DESCRIPTION** of the **HOST** message?",
    "Enter the **REACTION** to collect users:",
    "Enter the **TITLE** of the **PAIR** message:",
    "Enter the **DESCRIPTION** of the **PAIR** message:"
)


def set_pair_embed(ctx, userslist, msg_list):
    br = "\n"
    emoji = '\U0001F538'
    if len(userslist) > 2:
        pair_title = f"{msg_list[4]}"
        pair_desc = f"{' '.join(user.mention + br if i % 2 != 0 else user.mention + emoji for i, user in enumerate(userslist)) + br + msg_list[5]} "

    else:
        pair_title = msg_list[4] + "\n"
        pair_desc = "No pairings available. Try again when more users react to the host message."

    embed = discord.Embed(title=pair_title,
                          description=pair_desc,
                          color=0xFF5733)
    embed.set_author(name="Pear", url="https://github.com/kgatineau/pear_discord_bot",
                     icon_url="https://i.ibb.co/2y03dJ5/Pngtree-meb-style-yellow-cute-pear-5867760-1.png")
    embed.set_footer(text=f"Pear generated by: {ctx.author.display_name}")
    return embed


def export_data(message, answers):
    with open('root_message.csv', 'w', encoding="utf-8", newline='') as f:
        writer = csv.writer(f)
        writer.writerow([str(message.id)] + answers)


def import_data():
    list_msg = pd.read_csv(r'root_message.csv')
    msg_list = list(list_msg)
    print(msg_list)
    return msg_list


def create_prompt_embed(i, prompt, answers):
    colours = (
        0xff0000,
        0xffa700,
        0xfff400,
        0xa3ff00,
        0x2cba00
    )

    if len(answers) < 5:
        print(len(answers))
        prompt_t = f"Configuration - Step {i + 1} of 5"
        prompt_d = prompt
        colour = colours[i]
    else:
        prompt_t = answers[0]
        prompt_d = answers[1]
        colour = 0x2cba00

    em = discord.Embed(
        title=prompt_t,
        description=prompt_d,
        color=colour)
    em.set_author(name="Pear", url="https://github.com/kgatineau/pear_discord_bot",
                  icon_url="")
    config_fields(i, em, answers)
    em.set_footer(text="Pear - the Discord User Pairing Bot")
    return em


def config_fields(i_count, embed_, answers):
    match i_count:
        case 0:
            return ""
        case 1:
            embed_.add_field(name="Host Message", value="Title: ✅️", inline=False)
        case 2:
            embed_.add_field(name="Host Message", value="Title: ✅️\nDescription: ✅️", inline=False)
        case 3:
            embed_.add_field(name="Host Message", value=f"Title: ✅️\nDescription: ✅️\nReaction: {answers[2]} ",
                             inline=False)
        case 4:
            embed_.add_field(name="Host Message", value=f"Title: ✅️\nDescription: ✅️\nReaction: {answers[2]} ",
                             inline=True)
            embed_.add_field(name="Pair Message", value=f"Title: ✅️", inline=True)
